# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-05-21 14:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0008_story'),
    ]

    operations = [
        migrations.CreateModel(
            name='Circle',
            fields=[
                ('circle_id', models.AutoField(primary_key=True, serialize=False)),
                ('duration', models.IntegerField(blank=True)),
                ('is_active', models.BooleanField(default=False)),
                ('album_image', models.TextField()),
                ('teller_image', models.TextField()),
                ('scheduled_time', models.DateTimeField(blank=True)),
                ('created_date', models.DateTimeField(blank=True)),
                ('updated_date', models.DateTimeField()),
                ('live_stream_url', models.TextField()),
                ('last_index', models.IntegerField()),
                ('group_access', models.TextField(blank=True)),
                ('vod_stream_url', models.TextField(blank=True)),
                ('on_demand_id', models.UUIDField(default=uuid.uuid1, unique=True)),
                ('status', models.TextField(default='NOT_STARTED')),
                ('on_demand_status', models.TextField(default='NOT_AVAILABLE')),
                ('story', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restapi.Story')),
            ],
            options={
                'db_table': 'circle',
            },
        ),
    ]
