# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-05-21 14:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0009_circle'),
    ]

    operations = [
        migrations.AddField(
            model_name='circle',
            name='teller_name',
            field=models.TextField(blank=True),
        ),
    ]
