# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-05-21 15:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0010_circle_teller_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='circle',
            name='last_index',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='circle',
            name='live_stream_url',
            field=models.TextField(blank=True, null=True),
        ),
    ]
