# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-05-21 17:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0011_auto_20180521_1521'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='circle',
            name='is_active',
        ),
    ]
